title: "Melodía - Documentación"
description: "Documentación centralizada del Grupo 8"
url: "https://fiuba-ingsoft2-grupo8.github.io"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
color_scheme: light

aux_links:
  "Repositorio organización":
    - "https://github.com/fiuba-ingsoft2-grupo8"

nav_external_links:
  - title: "App Mobile"
    url: "https://github.com/fiuba-ingsoft2-grupo8/app-mobile/blob/main/Readme.md"
    opens_in_new_tab: true
  - title: "Backoffice"
    url: "https://github.com/fiuba-ingsoft2-grupo8/backoffice/blob/main/README.md"
    opens_in_new_tab: true
  - title: "Content API"
    url: "https://github.com/fiuba-ingsoft2-grupo8/content-api/blob/main/README.md"
    opens_in_new_tab: true
  - title: "Notifications API"
    url: "https://github.com/fiuba-ingsoft2-grupo8/notifications-api/blob/main/README.md"
    opens_in_new_tab: true
  - title: "Player API"
    url: "https://github.com/fiuba-ingsoft2-grupo8/player-api/blob/main/README.md"
    opens_in_new_tab: true
  - title: "User API"
    url: "https://github.com/fiuba-ingsoft2-grupo8/user-api/blob/main/README.md"
    opens_in_new_tab: true
